#!/usr/bin/env bash

die () { printf 'fatal: %b\n' "$@" >&2; exit 1; }

first_line_of_file () {
	mapfile -tn 1 line < "$1"
	printf '%s\n' "${line[@]}"
}

build_page () {
	filename=${1##*/}
	html="${filename/%.md/.html}"
	[[ $html -ot $1 ]] || return
	printf '%s\n' "    GEN         ${html}"

	if [[ $html != index.html ]]; then
		header="<a href='index.html'>Home</a>"
	fi

	first_line="$(first_line_of_file $1)"
	# The first line of a man page in markdown starts with a % character
	[[ $first_line == *%* ]] && header="${header}<br>${first_line#%}"

	printf '%b' "${template/'{{content}}'/$header$(pandoc "$1")}" >"${html}"
	header=
}

build_src_pages () {
	template="$(<"src/template.html")"
	for md in src/*.md; do
		build_page "${md}"
	done
}

build_man_pages () {
	if ! [[ -d ../jgmenu ]]; then
		printf 'warn: %b\n' "Need jgmenu next to jgmenu.github.io to build man pages" >&2
		return
	fi
	template="$(sed -e 's/sans-serif/monospace/' src/template.html)"
	for md in ../jgmenu/docs/manual/*.md; do
		build_page "${md}"
	done
}

main () {
	build_src_pages
	build_man_pages
}

main "$@"
