#!/usr/bin/env bash

die () {
	printf 'fatal: %b\n' "$@" >&2
	exit 1
}

generate_html () {
	local filename html

	filename=${1##*/}
	html="${filename/%.md/.html}"
	[[ $html -ot $1 ]] || return
	printf '%s\n' "    GEN         ${filename}"
	pandoc -s --css="src/manual.css" \
	       -o "${html}" "$1"
	       #--from=markdown_strict+backtick_code_blocks+pipe_tables+pandoc_title_block \
}

main () {
	[[ -d ../jgmenu ]] || die "need jgmenu next to jgmenu.github.io/"
	for md in ../jgmenu/docs/manual/*.md
	do
		generate_html "${md}"
	done
}

main "$@"
